// <auto-generated />
using System;
using AppeltjeEitje.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AppeltjeEitje.Migrations
{
    [DbContext(typeof(AppelEiContext))]
    partial class AppelEiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AppeltjeEitje.Data.Entities.Groep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naam");

                    b.HasKey("Id");

                    b.ToTable("Groepen");
                });

            modelBuilder.Entity("AppeltjeEitje.Data.Entities.Persoon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Achternaam");

                    b.Property<string>("Emailadres");

                    b.Property<DateTime>("GeboorteDatum");

                    b.Property<int?>("GroepId");

                    b.Property<DateTime>("Inschrijfdatum");

                    b.Property<string>("Notities");

                    b.Property<string>("Telefoonnummer");

                    b.Property<string>("Voornaam");

                    b.HasKey("Id");

                    b.HasIndex("GroepId");

                    b.ToTable("Personen");
                });

            modelBuilder.Entity("AppeltjeEitje.Data.Entities.Persoon", b =>
                {
                    b.HasOne("AppeltjeEitje.Data.Entities.Groep")
                        .WithMany("Personen")
                        .HasForeignKey("GroepId");
                });
#pragma warning restore 612, 618
        }
    }
}
